---
- name: Mettre à jour les paquets
  apt:
    update_cache: true
    upgrade: dist

- name: Installer les outils de base
  apt:
    name:
      - curl
      - vim
      - git
      - htop
      - net-tools
    state: present

- name: Configurer le timezone
  timezone:
    name: Europe/Brussels

- name: Déplacer SSH sur port 2222
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port '
    line: "Port 2222"
  notify: Restart SSH