---
# Cowrie uniquement sur la VM cowrie
- name: Déployer Cowrie
  hosts: cowrie
  become: true
  roles:
    - honeypot/cowrie

# OpenCanary sur les 3 VMs opencanary
- name: Déployer OpenCanary
  hosts: opencanary,opencanary2,opencanary3
  become: true
  roles:
    - honeypot/opencanary

# Dionaea uniquement sur la VM dionaea
- name: Déployer Dionaea
  hosts: dionaea
  become: true
  roles:
    - honeypot/dionaea