[vlan10]
cowrie      ansible_host=10.1.10.10             # nom logique = IP
opencanary  ansible_host=10.1.10.11
dionaea     ansible_host=10.1.10.12

[vlan20]
opencanary2  ansible_host=10.1.20.10

[vlan30]
opencanary3  ansible_host=10.1.30.10

[honeypots:children]
vlan10
vlan20
vlan30

# si vous voulez ajoutez des variables crée un fichier all.yml et ecriver vos variables sensibles dedans il y a un fichier all.yml.exemple avec les variables utiliser pour le projet
